---
- name: lineinfile usage example
  hosts: localhost
  tasks:
  - name: change resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver 8.8.8.8'
    notify: restart_network
  - name: configure sshd
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
    notify:
      restart_sshd

  handlers:
  - name: restart_sshd
    service:
      name: sshd
      state: restarted
  - name: restart_network
    service:
      name: NetWorkManager
      state: restarted

