---
- name: Setting up the Control Node
  hosts: control
  #strategy: free
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=control.rhce-ex294.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
      generate_ssh_key: yes
      force: yes
  - name: Allow user to run all command without password
    copy:
      dest: /etc/sudoers.d/user
      content: "user  ALL=(ALL)  NOPASSWD:ALL"
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Fixing Resolv File
    lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver 8.8.8.8'
      state: present
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n10.0.0.10 repo.rhce-ex294.com repo\n10.0.0.100 control.rhce-ex294.com control\n10.0.0.101 node1.rhce-ex294.com node1\n10.0.0.102 node2.rhce-ex294.com node2\n10.0.0.103 node3.rhce-ex294.com node3\n10.0.0.104 node4.rhce-ex294.com node4"
      force: yes
  - name: Erasing Repos
    file: 
      path: /etc/yum.repos.d/*
      state: absent
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Adding the rhel-system-repos.rpm
    copy:
      src: rhel-system-roles-1.0.1-1.el8.noarch.rpm
      dest: /home/vagrant
      owner: vagrant
      group: vagrant
      mode: "0775"
  - name: Building Repo File
    copy:
      dest: /etc/yum.repos.d/ipa.repo
      content: "[base]\nname=Base\nbaseurl=http://repo/mnt/BaseOS\ngpgcheck=0\nenabled=1\n\n[apps]\nname=Apps\nbaseurl=http://repo/mnt/AppStream\ngpgcheck=0\nenabled=1\n\n[Automation]\nname=Automation\nbaseurl=http://repo/automation/ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms\ngpgcheck=0\nenabled=1"
      force: yes
    tags: repo
  - name: Starting services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - firewalld
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http 
      - https 
      - ntp 
      - dns
      - ftp
  - name: Reloading Firewall
    service: name=firewalld state=restarted
  #- name: Configuring network
  #  shell: nmcli con mod 'System eth1' ipv4.addresses 10.0.0.100/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search rhce-ex294.com ipv4.method manual
  # - name: Reloaded Network
  #   service:
  #     name: NetworkManager
  #     state: restarted
#  - name: Generating RSA Key
#    command : ssh-keygen -q -t rsa -f /home/user/.ssh/id_rsa -C "" -N ""
#    become: yes
#    become_user: user
  - name: Adjusting services
    selinux:
      state: permissive
      policy: targeted
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
#  - name: Erasing Repos
#    file: 
#      path: /etc/yum.repos.d/*
#      state: absent
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #    _____ ____  _   _ _______ _____   ____  _      
        #   / ____/ __ \| \ | |__   __|  __ \ / __ \| |     
        #  | |   | |  | |  \| |  | |  | |__) | |  | | |     
        #  | |   | |  | | . ` |  | |  |  _  /| |  | | |     
        #  | |___| |__| | |\  |  | |  | | \ \| |__| | |____ 
        #   \_____\____/|_| \_|  |_|  |_|  \_\\____/|______|
        '"#
        #
        # You are logged into \"`hostname`\" as the \"`whoami`\" account.
        # This system is running `cat /etc/redhat-release`
        #
        # Repo/AppStream 
        # Available to use from http://repo.rhce-ex294.com/BaseOS and http://repo.rhce-ex294.com/AppStream
        "
  - name: Install additional software
    ansible.builtin.dnf:
      name: 
        - git
        - tree
      # - json_pp
      state: present
  # create dir for repo if not exists
  - name: create empty dir for repo
    ansible.builtin.file:
      path: /vagrant/home/rhce-ex294
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0775
  # check that dir is empty, if not skip git clone
  - name: check if repo exists
    ansible.builtin.stat:
      path: /home/vagrant/rhce-ex294
    register: filesFound

  # update: no means the repo will only be cloned if it doesn't exist 
  - name: Clone Repository
    ansible.builtin.git:
      repo: https://github.com/jfgsilva/rhce-ex294.git
      dest: /home/vagrant/rhce-ex294
      update: no
    when: filesFound.stat.exists == false

