---
- name: Setting Up Node 4
  hosts: node4
  #strategy: free
  gather_facts: False
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=node4.rhce-ex294.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Allow user to run all command without password
    copy:
      dest: /etc/sudoers.d/user
      content: "user  ALL=(ALL)  NOPASSWD:ALL"
      force: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Adjusting services
    selinux:
      state: permissive
      policy: targeted
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6localhost6.localdomain6\n10.0.0.10 repo.rhce-ex294.com repo\n10.0.0.100 control.rhce-ex294.com control\n10.0.0.101 node1.rhce-ex294.com node1\n10.0.0.102 node2.rhce-ex294.com node2\n10.0.0.103 node3.rhce-ex294.com node3\n10.0.0.104 node4.rhce-ex294.com node4"
      force: yes
  - name: Erasing Repos
    file: 
      path: /etc/yum.repos.d/*
      state: absent
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    copy:
      dest: /etc/yum.repos.d/ipa.repo
      content: "[base]\nname=Base\nbaseurl=http://repo/mnt/BaseOS\ngpgcheck=0\nenabled=1\n\n[apps]\nname=Apps\nbaseurl=http://repo/mnt/AppStream\ngpgcheck=0\nenabled=1"
      force: yes
    tags: repo
  #- name: Configuring network
  #  command: nmcli con mod 'System eth1' ipv4.addresses 10.0.0.104/24 ipv4.gateway 192.168.55.1 ipv4.method manual
  # - name: Restarting Network
  #   service: name=NetworkManager state=restarted
  # - name: Enabling IPV6
  #   sysctl:
  #     name: "{{ item }}"
  #     value: '0'
  #     sysctl_set: yes
  #   with_items:
  #     - net.ipv6.conf.lo.disable_ipv6
  #     - net.ipv6.conf.all.disable_ipv6
  - name: Environment Packages Installed
    yum:
      name: man-pages
      state: present 
    register: yum_sleeper
  - name: Environment Packages Installed.
    yum: name=man-pages state=present 
    register: yum_sleeper
  - name: Starting services
    service: name=firewalld enabled=true state=started
  - name: Fixing Resolv File
    lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver 8.8.8.8'
      state: present
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  # - name: Erasing Repos
  #   file: 
  #     path: /etc/yum.repos.d/*
  #     state: absent
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #   _   _  ____  _____  ______ _  _   
        #  | \ | |/ __ \|  __ \|  ____| || |  
        #  |  \| | |  | | |  | | |__  | || |_ 
        #  | . ` | |  | | |  | |  __| |__   _|
        #  | |\  | |__| | |__| | |____   | |  
        #  |_| \_|\____/|_____/|______|  |_|  
        '"#
        #
        # You are logged into \"`hostname`\" as the \"`whoami`\" account.
        # This system is running `cat /etc/redhat-release`
        #
        "
        
